/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CvRouteImport } from './routes/cv'
import { Route as SplatRouteImport } from './routes/$'
import { Route as StudyRouteRouteImport } from './routes/study/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyIndexRouteImport } from './routes/study/index'
import { Route as StudySlugRouteImport } from './routes/study/$slug'

const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRouteRoute = StudyRouteRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudyRouteRoute,
} as any)
const StudySlugRoute = StudySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StudyRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/study': typeof StudyRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/cv': typeof CvRoute
  '/study/$slug': typeof StudySlugRoute
  '/study/': typeof StudyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/cv': typeof CvRoute
  '/study/$slug': typeof StudySlugRoute
  '/study': typeof StudyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/study': typeof StudyRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/cv': typeof CvRoute
  '/study/$slug': typeof StudySlugRoute
  '/study/': typeof StudyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/study' | '/$' | '/cv' | '/study/$slug' | '/study/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/cv' | '/study/$slug' | '/study'
  id: '__root__' | '/' | '/study' | '/$' | '/cv' | '/study/$slug' | '/study/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudyRouteRoute: typeof StudyRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  CvRoute: typeof CvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof StudyRouteRoute
    }
    '/study/$slug': {
      id: '/study/$slug'
      path: '/$slug'
      fullPath: '/study/$slug'
      preLoaderRoute: typeof StudySlugRouteImport
      parentRoute: typeof StudyRouteRoute
    }
  }
}

interface StudyRouteRouteChildren {
  StudySlugRoute: typeof StudySlugRoute
  StudyIndexRoute: typeof StudyIndexRoute
}

const StudyRouteRouteChildren: StudyRouteRouteChildren = {
  StudySlugRoute: StudySlugRoute,
  StudyIndexRoute: StudyIndexRoute,
}

const StudyRouteRouteWithChildren = StudyRouteRoute._addFileChildren(
  StudyRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudyRouteRoute: StudyRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  CvRoute: CvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
